baseURL = 'https://xuanliu1226.github.io/site/'
languageCode = 'en-us'
title = 'ğŸ±'
paginate = 5
theme = 'PaperMod'
publishDir = 'docs'
googleAnalytics = "G-NYD9LZH1H5"
comments = true


[params]
  [params.homeInfoParams]
    Title = "çŒ«å’Œå¥½å¤©æ°”"
    Content = """A person striving to live fully | å¥½å¥½ç”Ÿæ´» ğŸ–¤"""
  [[params.socialIcons]]
    name = "email"
    url = "mailto:xuanliu1226@gmail.com"
  [[params.socialIcons]]
    name = "RSS"
    url= "https://xuanliu1226.github.io/site/"
  [[params.socialIcons]]
    name = "Instagram"
    url= "https://www.instagram.com/coraxuan.l/"
